
sudo: required
group: edge

services:
  - docker

env:
  global:
    - VERSION=${VERSION:-3.5}

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: test
      script:
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - sleep 30s
        - make test
        - docker-compose down

    - stage: push docker image
      if: branch = master
      script:
        - make
        - docker tag  ${USER}/carbon-c-relay:latest ${DOCKER_USERNAME}/docker-carbon-c-relay:latest
        - docker tag  ${USER}/carbon-c-relay:latest ${DOCKER_USERNAME}/docker-carbon-c-relay:${VERSION}
        #
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker push ${DOCKER_USERNAME}/docker-carbon-c-relay:latest
        - docker push ${DOCKER_USERNAME}/docker-carbon-c-relay:${VERSION}
        #
        - docker logout
